language: ar

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: ResponseSelector
    epochs: 30

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
    restrict_rules: true
  - name: MemoizationPolicy
    max_history: 3
