name: Rasa CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Rasa with full dependencies
        run: |
          pip install "rasa[full]"
          pip install psycopg2-binary  # إذا كنت تستخدم PostgreSQL مع Supabase

      - name: Train Rasa model
        run: |
          rasa train